#!/usr/bin/env node
// Generate static/_redirects for Cloudflare Pages.
//
// Reads each post's frontmatter from content/posts/*.md, takes the filename
// (without .md) as the WordPress.com flat slug, and the `url:` field as the
// Hugo permalink. Emits a `/{slug}/  {url}  301` line per post, plus a
// hand-curated header of wildcard rules for categories, feeds, archives,
// and retired WP infrastructure paths.
//
// Run via:  node scripts/generate_redirects.mjs
// Output :  static/_redirects  (Hugo copies this verbatim into public/)

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const POSTS_DIR = join(ROOT, "content", "posts");
const OUT_PATH = join(ROOT, "static", "_redirects");

// Static rule blocks. Order matters: Cloudflare Pages applies first match.
//
// CRITICAL constraints (learned from production testing):
//   1. CF Pages percent-encodes the incoming URL before matching _redirects.
//      Rules with raw UTF-8 paths NEVER match — every non-ASCII char must
//      be percent-encoded in the source column.
//   2. Placeholders (:year, :slug) accept ANY string — they don't validate
//      against \\d+ etc. Pure-placeholder rules like /:year/:month/ silently
//      eat ALL two-segment URLs (/wp-login.php, /foo/bar/...). Avoid them.
//   3. CF Pages \`410\` status with a destination is unreliable in practice;
//      let those URLs fall through to the natural 404 instead.
//
// All non-ASCII paths below have been pre-encoded; the per-post auto-gen
// section also runs encodeURI() on every slug.
const HEADER = `# Auto-generated by scripts/generate_redirects.mjs — DO NOT edit by hand.
# Regenerate after content changes:  node scripts/generate_redirects.mjs
#
# Cloudflare Pages _redirects syntax:  <from>  <to>  <status>
# All non-ASCII paths are percent-encoded (CF Pages matches against the
# encoded URL, raw UTF-8 source paths never match).

# === 1. Site / comments / category feeds → site RSS ===
/feed/             /index.xml   301
/feed              /index.xml   301
/comments/feed/    /index.xml   301
/comments/feed     /index.xml   301
/category/*/feed/  /categories/:splat/   301
/category/*/feed   /categories/:splat/   301

# === 2. Categories (with pagination) — prefix splat is safe ===
/category/*/page/:n/  /categories/:splat/page/:n/   301
/category/*/page/:n   /categories/:splat/page/:n/   301
/category/*/          /categories/:splat/           301
/category/*           /categories/:splat/           301

# === 3. Per-post RSS feeds → article page ===
# Note: /:year/:month/:day/:slug/feed/ matches any 5-segment URL ending in
# "feed" — acceptable because Hugo doesn't generate such paths and false
# matches just redirect to a non-existent article (also 404, no harm).
/:year/:month/:day/:slug/feed/   /:year/:month/:day/:slug/   301
/:year/:month/:day/:slug/feed    /:year/:month/:day/:slug/   301

# === 4. Manually-listed calendar archives (only the ones GSC reported) ===
# DO NOT add a wildcard /:year/:month/ rule — it matches ANY two-segment URL.
# Add specific years/months here as GSC reports them.
/2018/10/   /archives/   301
/2018/10    /archives/   301

# === 5. Manual overrides for WordPress slug duplicates (\`-N\` suffix) ===
# WP auto-suffixes when slugs collide. Add lines here as GSC reports them.
# Paths must be percent-encoded.
/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C-3/   /2025/07/25/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C/   301
/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C-2/   /2025/07/25/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C/   301

# === 6. Per-post WP flat-slug URLs (auto-generated below, percent-encoded) ===
`;

function extractUrl(yamlBlock) {
  const m = yamlBlock.match(/^url:\s*"?([^"\n]+?)"?\s*$/m);
  return m ? m[1].trim() : null;
}

function readFrontmatter(filePath) {
  const text = readFileSync(filePath, "utf8");
  if (!text.startsWith("---")) return null;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return null;
  return text.slice(3, end);
}

function buildPostMap() {
  const files = readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_"));
  const entries = [];
  let skipped = 0;
  for (const file of files) {
    const slug = basename(file, extname(file));
    const fm = readFrontmatter(join(POSTS_DIR, file));
    if (!fm) {
      skipped++;
      continue;
    }
    const url = extractUrl(fm);
    if (!url) {
      skipped++;
      continue;
    }
    // Skip if old slug already equals the new path (no redirect needed).
    if (url === `/${slug}/` || url === `/${slug}`) continue;
    entries.push({ slug, url: url.endsWith("/") ? url : url + "/" });
  }
  return { entries, skipped, total: files.length };
}

function formatRedirectLine({ slug, url }) {
  // CF Pages matches against percent-encoded incoming URLs, so non-ASCII
  // paths in _redirects must also be percent-encoded. encodeURI() encodes
  // the chars CF needs while leaving / safe.
  const from = `/${encodeURI(slug)}/`;
  const to = encodeURI(url);
  return `${from.padEnd(80)} ${to.padEnd(80)} 301`;
}

function main() {
  if (!existsSync(POSTS_DIR)) {
    console.error(`Posts directory not found: ${POSTS_DIR}`);
    process.exit(1);
  }
  const { entries, skipped, total } = buildPostMap();
  const lines = entries.map(formatRedirectLine).join("\n");
  const out = HEADER + lines + "\n";

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, "utf8");

  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  ${total} posts scanned`);
  console.log(`  ${entries.length} per-post redirects emitted`);
  if (skipped) console.log(`  ${skipped} skipped (missing frontmatter / url:)`);
}

main();
