#!/usr/bin/env node
// Generate static/_redirects for Cloudflare Pages.
//
// Per-post WP→Hugo URL redirects are NOT in this file — they live as Hugo
// `aliases:` in each post's frontmatter (see scripts/add_wp_aliases.mjs)
// because CF Pages caps free-tier _redirects at 100 rules and we have 785
// posts. This file only handles classes of URLs aliases can't represent:
// site-level feeds, /category/* prefix, calendar archives, and a few
// hand-curated WP slug duplicates.
//
// Run via:  node scripts/generate_redirects.mjs
// Output :  static/_redirects  (Hugo copies it into public/ at build time)

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_PATH = join(ROOT, "static", "_redirects");

// CF Pages _redirects rules. Order matters: first match wins.
//
// CRITICAL constraints (learned from production testing):
//   1. CF Pages percent-encodes the incoming URL before matching, so
//      non-ASCII source paths must be pre-encoded.
//   2. Pure placeholders like /:year/:month/ silently eat ALL two-segment
//      URLs (no \\d+ constraint). Avoid them — list specific paths instead.
//   3. CF Pages free tier caps at 100 rules. Total here must stay <100.
//   4. CF Pages 410-with-destination is unreliable; let those URLs natural-404.
const BODY = `# Auto-generated by scripts/generate_redirects.mjs — DO NOT edit by hand.
# Regenerate after content changes:  node scripts/generate_redirects.mjs
#
# Per-post slug redirects live in each post's frontmatter as Hugo aliases,
# not here — see scripts/add_wp_aliases.mjs. This file is for classes of
# URLs that aliases can't express.

# === 1. Site / comments / category feeds → site RSS ===
/feed/             /index.xml   301
/feed              /index.xml   301
/comments/feed/    /index.xml   301
/comments/feed     /index.xml   301
/category/*/feed/  /categories/:splat/   301
/category/*/feed   /categories/:splat/   301

# === 2. Categories (with pagination) — prefix splat is safe ===
/category/*/page/:n/  /categories/:splat/page/:n/   301
/category/*/page/:n   /categories/:splat/page/:n/   301
/category/*/          /categories/:splat/           301
/category/*           /categories/:splat/           301

# === 3. Per-post RSS feeds → article page ===
# Matches any 5-segment URL ending in "feed". False matches just redirect
# to a non-existent article (also 404, no harm).
/:year/:month/:day/:slug/feed/   /:year/:month/:day/:slug/   301
/:year/:month/:day/:slug/feed    /:year/:month/:day/:slug/   301

# === 4. Manually-listed calendar archives (only the ones GSC reported) ===
# Do NOT add a wildcard /:year/:month/ rule — it eats every two-segment URL.
/2018/10/   /archives/   301
/2018/10    /archives/   301

# === 5. WordPress slug duplicates (\`-N\` suffix) ===
# WP auto-suffixes when slugs collide. The base article (no suffix) is
# handled by Hugo aliases; only the duplicates need a manual rule. Add
# more here as GSC reports them. Paths must be percent-encoded.
/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C-3/   /2025/07/25/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C/   301
/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C-2/   /2025/07/25/%E9%92%A2%E5%85%89%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C/   301
`;

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, BODY, "utf8");

const ruleCount = BODY.split("\n").filter(
  (line) => line.trim() && !line.startsWith("#"),
).length;
console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${ruleCount} active rules (CF Pages free-tier cap: 100)`);
