#!/usr/bin/env node
// Generate static/_redirects for Cloudflare Pages.
//
// Reads each post's frontmatter from content/posts/*.md, takes the filename
// (without .md) as the WordPress.com flat slug, and the `url:` field as the
// Hugo permalink. Emits a `/{slug}/  {url}  301` line per post, plus a
// hand-curated header of wildcard rules for categories, feeds, archives,
// and retired WP infrastructure paths.
//
// Run via:  node scripts/generate_redirects.mjs
// Output :  static/_redirects  (Hugo copies this verbatim into public/)

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const POSTS_DIR = join(ROOT, "content", "posts");
const OUT_PATH = join(ROOT, "static", "_redirects");

// Static rule blocks. Order matters: Cloudflare Pages applies first match.
// 410 retirements come first so /wp-includes/* never falls through into
// later wildcards. Specific feed rules come before generic category rules.
const HEADER = `# Auto-generated by scripts/generate_redirects.mjs — DO NOT edit by hand.
# Regenerate after content changes:  node scripts/generate_redirects.mjs
#
# Cloudflare Pages _redirects syntax:  <from>  <to>  <status>

# === 1. Permanently retired WordPress / Cloudflare infrastructure → 410 Gone ===
/wp-includes/*              /404.html  410
/wp-content/plugins/*       /404.html  410
/wp-content/themes/*        /404.html  410
/wp-json/*                  /404.html  410
/xmlrpc.php                 /404.html  410
/wp-login.php               /404.html  410
/wp-admin/*                 /404.html  410
/cdn-cgi/l/email-protection /404.html  410

# === 2. Per-post RSS feeds → article page ===
/:year/:month/:day/:slug/feed/   /:year/:month/:day/:slug/   301
/:year/:month/:day/:slug/feed    /:year/:month/:day/:slug/   301

# === 3. Site-level / comments / category feeds → site RSS ===
/feed/             /index.xml   301
/feed              /index.xml   301
/comments/feed/    /index.xml   301
/comments/feed     /index.xml   301
/category/*/feed/  /categories/:splat/   301
/category/*/feed   /categories/:splat/   301

# === 4. Categories (with pagination) ===
/category/*/page/:n/  /categories/:splat/page/:n/   301
/category/*/page/:n   /categories/:splat/page/:n/   301
/category/*/          /categories/:splat/           301
/category/*           /categories/:splat/           301

# === 5. Year/month/day archives (Hugo has no calendar archive pages) ===
/:year/:month/:day/   /archives/   301
/:year/:month/:day    /archives/   301
/:year/:month/        /archives/   301
/:year/:month         /archives/   301

# === 6. Manual overrides for WordPress slug duplicates (\`-N\` suffix) ===
# WordPress auto-suffixes when slugs collide. Add lines here as GSC reports them.
/钢光纪念相册-3/   /2025/07/25/钢光纪念相册/   301
/钢光纪念相册-2/   /2025/07/25/钢光纪念相册/   301

# === 7. Per-post WP flat-slug URLs (auto-generated below) ===
`;

function extractUrl(yamlBlock) {
  const m = yamlBlock.match(/^url:\s*"?([^"\n]+?)"?\s*$/m);
  return m ? m[1].trim() : null;
}

function readFrontmatter(filePath) {
  const text = readFileSync(filePath, "utf8");
  if (!text.startsWith("---")) return null;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return null;
  return text.slice(3, end);
}

function buildPostMap() {
  const files = readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_"));
  const entries = [];
  let skipped = 0;
  for (const file of files) {
    const slug = basename(file, extname(file));
    const fm = readFrontmatter(join(POSTS_DIR, file));
    if (!fm) {
      skipped++;
      continue;
    }
    const url = extractUrl(fm);
    if (!url) {
      skipped++;
      continue;
    }
    // Skip if old slug already equals the new path (no redirect needed).
    if (url === `/${slug}/` || url === `/${slug}`) continue;
    entries.push({ slug, url: url.endsWith("/") ? url : url + "/" });
  }
  return { entries, skipped, total: files.length };
}

function formatRedirectLine({ slug, url }) {
  // Cloudflare Pages handles UTF-8 paths verbatim. No percent-encoding needed.
  // Pad source column for human readability; CF accepts any whitespace.
  const from = `/${slug}/`;
  return `${from.padEnd(60)} ${url.padEnd(50)} 301`;
}

function main() {
  if (!existsSync(POSTS_DIR)) {
    console.error(`Posts directory not found: ${POSTS_DIR}`);
    process.exit(1);
  }
  const { entries, skipped, total } = buildPostMap();
  const lines = entries.map(formatRedirectLine).join("\n");
  const out = HEADER + lines + "\n";

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, "utf8");

  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  ${total} posts scanned`);
  console.log(`  ${entries.length} per-post redirects emitted`);
  if (skipped) console.log(`  ${skipped} skipped (missing frontmatter / url:)`);
}

main();
